name: Veracode

on:
 # Enables manual runs
  workflow_dispatch:

jobs:
  Veracode:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Veracode
        run: |
         curl -fsS https://tools.veracode.com/veracode-cli/install | sh

      - name: Package App
        run: |         
         ./veracode package -s ./ -a
         ls -lah
         
      - name: ls
        run: |         
         ls -lah
